export enum ColorFormatTo {
  RGB = "rgb",
  // RGBA = "rgba",
  HEX = "hex",
  // HEXA = "hexa",
  HSL = "hsl",
  // HSLA = "hsla",
  CMYK = "cmyk",
  // CMYKA = "cmyka",
  HWB = "hwb",
  // HWBA = "hwba",
  HEX0X = "hex0x",
  NAMED = "named",
  LAB = "lab",
  LCH = "lch",
  OKLAB = "oklab",
  OKLCH = "oklch",
}

export enum ColorFormatFrom {
  RGB = "rgb",
  RGBA = "rgba",
  HSL = "hsl",
  HSLA = "hsla",
  CMYK = "device-cmyk",
  NAMED = "named",
  HEX = "hex",
  HEX_0X = "hex0x",
  HWB = "hwb",
  LAB = "lab",
  LCH = "lch",
  OKLAB = "oklab",
  OKLCH = "oklch",
}

export enum CommandType {
  LINE = "LINE",
  SELECTION = "SELECTION",
  FILE = "FILE",
}

export enum TemplateColorFragments {
  name = "name",
  hex = "hex",
  aH = "aH",
  HEX = "HEX",
  AH = "AH",
  a = "a",
  r = "r",
  g = "g",
  b = "b",
  h = "h",
  s = "s",
  l = "l",
  c = "c",
  m = "m",
  y = "y",
  k = "k",
  v = "v",
}
