name: Update README
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      - name: Update README
        id: readme
        uses: jeronimoek/markdown-vscode-contributions-action@v1.0.12
        with:
          github-token: ${{ secrets.github_token }}

      - name: Get the output README
        run: echo "The new readme is ${{ steps.readme.outputs.markdown_output }}"
