name: Update README
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        id: readme
        uses: jeronimoek/markdown-vscode-contributions-action@v1.0.13
        with:
          github-token: ${{ secrets.github_token }}
